<?php
include('connection.php');

// Check if the user email is provided
if (isset($_POST['user_email'])) {
    $userEmail = mysqli_real_escape_string($conn, $_POST['user_email']);

    // Your logic to send an email using PHPMailer or another library
    // Example using mail() function:
    $subject = "Account Deactivation";
    $message = " Dear user, your account is scheduled for deactivation. 
    VACCUNA Terms and Conditions
    Effective Date: [December, 2023]
    These Terms and Conditions govern your use of the VACCUNA web-based Child Vaccination Management and Appointment System. By using VACCUNA, you agree to abide by these Terms. Please read them carefully.

        1. System Functionality and Vaccination Intervals:
        1a. VACCUNA automatically maintains 4–6-week intervals between each vaccine to ensure proper vaccination scheduling when users make appointments.
        2. Handling Pediatric Care:
        2a. VACCUNA is prepared to handle situations where a child becomes a toddler and requires a pediatrician. It provides advice and information from certified pediatricians, sourced from legitimate medical sources.
        3. Printable Vaccination Cards:
        3a. The printable vaccination card generated by VACCUNA includes a signature or symbol indicating that the child received vaccinations from the local barangay health center.
        5. Parent Dashboard:
        5a. The parent dashboard within VACCUNA provides immediate access to all necessary information required for managing their child's vaccinations.
        6. Calendar Options for Parents:
        6a. Parents have access to calendar options, allowing them to schedule appointments at the local barangay health center and view clinic or doctor availability.
        7. Risk Information:
        7a. Parents are informed about the potential risks associated with delayed or missed vaccinations, providing them with essential health information.
        8. Reporting Missed/Delayed Cases:
        8a. VACCUNA routes reports or data on missed/delayed vaccination cases to appropriate authorities, ensuring prompt attention and action.
        9. Account Deletion Policy:
        9a. VACCUNA may delete user accounts after a period of inactivity. Users will be reminded of this policy through their registered email address, with a notification that their accounts will be deleted.
        
        10. Compliance with Local Regulations:
        10a. Users are expected to comply with all local laws and regulations governing vaccinations and healthcare practices.
        11. Privacy and Data Security:
        11a. VACCUNA maintains user data with the utmost care. Refer to our Privacy Policy for details on how user data is collected, used, and protected.
        12. Termination:
        12a. VACCUNA reserves the right to terminate or suspend user accounts for violations of these Terms or for any other reason.
        13. Modifications to Terms:
        13a. VACCUNA may modify these Terms from time to time. Users will be notified of such changes through the platform, and continued use constitutes acceptance of the updated Terms.
        14. Contact Information:
        14a. For questions or concerns about these Terms or the use of VACCUNA, please contact us at Contact Us Tab.
        By using VACCUNA, you acknowledge that you have read and understood these Terms and agree to be bound by them. If you do not agree with any part of these Terms, please refrain from using VACCUNA.
";
    $headers = "From: support@vaccuna.online"; 

    if (mail($userEmail, $subject, $message, $headers)) {
        $response = array('success' => true, 'message' => 'Email sent successfully');
        echo json_encode($response);
    } else {
        $response = array('success' => false, 'message' => 'Error sending email');
        echo json_encode($response);
    }
} else {
    $response = array('success' => false, 'message' => 'User email not provided');
    echo json_encode($response);
}

mysqli_close($conn);
?>
